config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root 'homes#top'
  resources :users, only: [:show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
  end
  resources :posts do
    resources :tags, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, length: { maximum: 100 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :title, presence: true
  validates :destination, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def save_tag(sent_tags)
    current_tags = tags.pluck(:name) unless tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      new_tag = Tag.find_or_create_by(name: new)
      tags << new_tag
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :user

  validates :name, length: { minimum: 2 }, presence: true, uniqueness: true
  validates :age, presence: true
  validates :address, presence: true

  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end

  def follow(other_user)
    return if self == other_user
    relationships.find_or_create_by!(follow: other_user)
  end

  def unfollow(relationship_id)
    relationships.find(relationship_id).destroy!
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_up_path_for(resource)
    posts_path(resource)
  end

  def after_sign_in_path_for(resource)
    posts_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    #  binding.pry
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age, :address])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = @post.id
    comment.save
    redirect_to post_path(@post)
  end

  def destroy
    Comment.find_by(id: params[:id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id).destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.joins(:tags).distinct.page(params[:page]).per(3)
    @q = Post.ransack(params[:q])
    if params[:q].present?
      @posts = @q.result(distinct: true).page(params[:page]).per(3)
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_tags = @post.tags
    @like = Like.new
    @comment = Comment.new
    @other_user = @post.user_id
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list = params[:post][:name].split(',')
    if @post.save
      @post.save_tag(tag_list)
      redirect_to post_path(@post), notice: '投稿しました'
    else
      @posts = Post.all
      render 'index'
    end
  end

  def edit
    @post = Post.find(params[:id])
    @tag_list = @post.tags.pluck(:name).join(',')
    if @post.user != current_user
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    tag_list = params[:post][:name].split(',')
    if @post.update(post_params)
      @post.save_tag(tag_list)
      redirect_to post_path(@post), notice: '投稿内容更新しました'
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:image, :title, :destination, :body)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "更新完了しました。"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :age, :address, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h2 class="my-2">投稿編集</h2>
      <%= form_with model: @post, local:true do |f| %>
        <div class="form-group">
          <%= f.label :画像 %>
          <%= f.attachment_field :image, class: "form-control-file image" %>
        </div>
        <div class="form-group">
          <%= f.label :タイトル %>
          <%= f.text_field :title, class: "form-control title" %>
        </div>
        <div class="form-group">
          <%= f.label :旅行先 %>
          <%= f.text_field :destination, class: "form-control destination" %>
        </div>
        <div class="form-group">
          <%= f.label :思い出 %>
          <%= f.text_area :body, class: "form-control body" %>
        </div>
        <div class="form-group">
          <%= f.label :"タグ(,で区切ると複数タグ登録できます)" %>
          <%= f.text_field :name, value: @tag_list, class: "form-control name" %>
        </div>
        <div class="my-4">
          <%= f.submit "更新", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <%= render "searchs/form", q: @q, url: posts_path %>
    </div>
  </div>
  <div class="row">
    <div class="my-2">
      <h2>投稿一覧</h2>
    </div>
  </div>
  <div class="row">
    <% @posts.each do |post| %>
    　<div class="col-md-3 my-5">
    　   <div class="card">
          <p class="text-center my-2"><%= attachment_image_tag post, :image, width: '80%', height: '80%' %></p>
          <div class="card-body text-center">
            <h5>ユーザー名</h5>
            <p><%= post.user.name %></p>
            <h5>旅行先</h5>
            <p><%= post.destination %></p>
            <h5>タグ</h5>
            <% post.tags.each.with_index(1) do |tag,i| %>
              <%= tag.name %><%= "," unless i==post.tags.length %>
            <% end %>
            <p class="my-2">コメント件数: <%= post.comments.count %></p>
            <p><%= link_to '詳細', post_path(post) %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="mx-auto my-3">
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h2 class="my-2">新規投稿</h2>
      <%= form_with model: @post, local:true do |f| %>
        <div class="form-group">
          <%= f.label :画像 %>
          <%= f.attachment_field :image, class: "form-control-file image" %>
        </div>
        <div class="form-group">
          <%= f.label :タイトル %>
          <%= f.text_field :title, class: "form-control title" %>
        </div>
        <div class="form-group">
          <%= f.label :旅行先 %>
          <%= f.text_field :destination, class: "form-control destination" %>
        </div>
        <div class="form-group">
          <%= f.label :思い出 %>
          <%= f.text_area :body, class: "form-control body" %>
        </div>
        <div class="form-group">
          <%= f.label :"タグ(,で区切ると複数タグ登録できます)" %>
          <%= f.text_field :name, value: @tag_list, class: "form-control name" %>
        </div>
        <div class="my-4">
          <%= f.submit "投稿", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="my-2">
      <h2>投稿詳細</h2>
    </div>
  </div>
  <div class="d-flex mx-auto">
    <div class="row">
      <div class="text-center" style="width: 700px">
        <div class="my-4">
          <p><%= attachment_image_tag @post, :image, width: '70%', height: '70%' %></p>
          <p>ユーザー名: <%= @post.user.name %></p>
        </div>
      </div>
    </div>
    <div class-"row">
      <div class="text-left" style="width: 350px">
        <div class="my-4">
          <p class="mt-2">タイトル: <%= @post.title %></p>
          <p class="mt-2">旅行先: <%= @post.destination %></p>
          <p class="mt-2">思い出: <%= @post.body %></p>
          <p class="mt-2">タグ: <%= @post.tags.map(&:name).join(',') %></p>
          <p class="mt-2">いいね: <%= @post.likes.count %></p>
          <p class="mt-2">コメント件数: <%= @post.comments.count %></p>
          <% if @user.id != current_user.id %>
            <% if current_user.already_liked?(@post) %>
              <p><%= link_to "いいね!しない", post_like_path(@post), method: :delete, class: "btn btn-secondary" %></p>
            <% else %>
              <p><%= link_to "いいね!", post_likes_path(@post), method: :post,  class: "btn btn-secondary" %></p>
            <% end %>
          <% end %>
          <% unless current_user == @user %>
            <% if current_user.following?(@user) %>
              <p><%= link_to "フォローしない", user_relationship_path(current_user.relationships.find_by(follow: @user), post_id: @post.id), method: :delete, class: "btn btn-info" %></p>
            <% else %>
              <p><%= link_to "フォローする", user_relationships_path(user_id: current_user.id, follow: @other_user, post_id: @post.id), method: :post, class: "btn btn-info" %></p>
            <% end %>
          <% end %>
          <div class="new-comment">
            <%= form_with(model:[@post, @comment], local: true) do |f| %>
              <%= f.text_area :content, placeholder: "コメント入力", class: "form-control" %>
              <%= f.submit "送信" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto">
      <% if @post.user == current_user %>
        <p>
          <%= link_to '編集', edit_post_path(@post), class: "btn btn-sm btn-success" %>
          <%= link_to '削除', post_path(@post), method: :delete, class: "btn btn-sm btn-danger" %>
        </p>
      <% end %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="my-3">
      <h2>コメント一覧</h2>
    </div>
  </div>
  <div class="row">
    <table class="table table-borderless">
      <thead>
        <tr>
          <th>ユーザー名</th>
          <th>コメント</th>
        </tr>
      </thead>
      <tbody>
        <% @post.comments.each do |comment| %>
          <tr>
            <td><%= comment.user.name %></td>
            <td><%= comment.content %></td>
            <% if comment.user == current_user %>
              <td><%= link_to "削除", post_comment_path(comment.post, comment), method: :delete, class: "btn btn-danger" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h2 class="my-2">マイページﾞ編集</h2>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :ユーザー名 %>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <%= f.label :年齢 %>
          <%= f.text_field :age, class: "form-control age" %>
        </div>
        <div class="form-group">
          <%= f.label :居住地 %>
          <%= f.text_field :address, class: "form-control address" %>
        </div>
        <div class="my-4">
          <%= f.submit "更新", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <div class="mt-2">
        <h2>ﾏｲﾍﾟｰｼﾞ</h2>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto">
      <div class="my-3">
        <table class="table table-borderless">
          <tbody>
            <tr>
              <th>ユーザーID</th>
              <td><%= @user.name %></td>
            </tr>
            <tr>
              <th>年齢</th>
              <td><%= @user.age %></td>
            </tr>
            <tr>
              <th>居住地</th>
              <td><%= @user.address %></td>
            </tr>
            <tr>
              <th>フォロー数</th>
              <td><%= @user.followings.count %></td>
            </tr>
            <tr>
              <th>フォロワー数</th>
              <td><%= @user.followers.count %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <% if @user.id == current_user.id %>
    <div class="row">
      <div class="mx-auto">
        <p><%= link_to "編集", edit_user_path(@user), class: "btn btn-success" %></p>
      </div>
    </div>
  <% end %>
</div>